version: '3.4'

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_DB=${POSTGRES_DATABASE}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - ./.data/db:/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"